name: build
on: 
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --configuration Release dotnetinteractive-openapi.sln
    - name: Push Nuget
      run: dotnet nuget push "src/MfhSoft.DotNet.Interactive.OpenApi/bin/Release/MfhSoft.DotNet.Interactive.OpenApi.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      